# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
    - name: Home
      url: /#top
      weight: 10
    - name: News
      url: /post/
      weight: 20
    - name: Projects
      url: /project/
      weight: 30
    - name: Publications
      url: /publication/
      weight: 40
    - name: Contact
      url: /#contact
      weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs â†—"
    url: "https://docs.hugoblox.com"
    weight: 3
